image: java:8

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew clean build
